### ISSUE TITLE
Improve Top Page Stats

### ISSUE THREAD

**Issue by calendee** [simpleanalytics/roadmap#190] opened 2019-12-22 11:38 UTC
When viewing the stats for a specific page, the Referrals, Top Pages, Screen Widths, Countries still display information about the entire site - not just that individual page.

When viewing an individual page, it doesn't seem necessary to see "Top Pages".  I would also really love if the summary statistics were only for that specific page.

https://www.loom.com/share/644176e033c146b7a0acaf4eaace1342

**Comment by adriaanvanrossum** [comment] 2019-12-23 12:30
I think this is a duplicate of https://github.com/simpleanalytics/roadmap/issues/166, let me know if it is not! I will give a short update in the other issue.

**Closed by adriaanvanrossum** 2019-12-23 12:30 UTC

**Comment by calendee** [comment] 2019-12-23 12:45
Sure is!  Sorry I missed it.

**Comment by adriaanvanrossum** [comment] 2019-12-23 12:46
No worries! That's our job, not yours 😉
